name: Continuous Integration (CI)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Baixa o código do repositório para a máquina virtual
    - name: Checkout do código
      uses: actions/checkout@v4

    # 2. Simula um teste de validação (Verifica se o index.html existe)
    - name: Validar estrutura do projeto
      run: |
        if [ -f "main.tf" ]; then
          echo "Sucesso: O arquivo main foi encontrado!"
        else
          echo "Erro: Arquivo main.tf não encontrado."
          exit 1
        fi

    # 3. Simula uma validação de sintaxe simples (Linter)
    - name: Validar sintaxe HTML básica
      run: |
        grep -q "</html>" main.tf && echo "main tags fechadas corretamente."

    # 4. Gera e armazena o artefato do build para o CD utilizar
    - name: Upload do artefato de produção
      uses: actions/upload-artifact@v4
      with:
        name: site-producao
        path: site/
